#!/usr/bin/env ruby
require 'midTests/runTest'
ARGV.each do |test|
  run "midTests/#{test}.mid.gs"
end

def test_files
  Dir["midTests/*.mid.gs"]
end

if ARGV.empty?
  files = test_files
  puts "Testing #{files.length} items..."
  files.each { |file| run file }
end